apiVersion: v1
kind: Service
metadata:
  name: letsgo-service
  namespace: letsgo-ENVIRONMENT-ns
  labels:
    app: letsgo
    env: ENVIRONMENT
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: letsgo
    env: ENVIRONMENT
  type: LoadBalancer
