apiVersion: v1
kind: Service
metadata:
  name: letsgo-svc
  namespace: letsgo-ENVIRONMENT-ns
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: letsgo
    env: ENVIRONMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: letsgo-deployment
  namespace: letsgo-ENVIRONMENT-ns
  labels:
    app: letsgo
    env: ENVIRONMENT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letsgo
      env: ENVIRONMENT
  template:
    metadata:
      labels:
        app: letsgo
        env: ENVIRONMENT
    spec:
      containers:
        - name: letsgo
          image: jrmanes/letsgo:GIT_COMMIT
          # imagePullPolicy: Always
          resources:
            limits:
              cpu: "450m"
              memory: "450m"
            requests:
              cpu: "250m"
              memory: "250m"
          ports:
            - containerPort: 80
          # readinessProbe:
          #   httpGet:
          #     path: /health-check
          #     port: 80
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 80
