apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: letsgo-hpa-cpu
  namespace: letsgo-ENVIRONMENT-ns
  labels:
    app: letsgo
    env: ENVIRONMENT
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: letsgo-deployment
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 55
