apiVersion: v1
kind: Service
metadata:
  name: go-docker-clusterip
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  selector:
    app: go-docker
    env: prod
